/* Trader Editor Tools v0.1.3 | MIT | Generated by scripts/build.cjs */
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// src/markdown.js
var require_markdown = __commonJS({
  "src/markdown.js"(exports2, module2) {
    function linesOf(text) {
      const lines = [];
      const re = /([^\r\n]*)(\r\n|\n|\r|$)/g;
      let m;
      while ((m = re.exec(text)) && m[0]) {
        lines.push({ text: m[1], eol: m[2], start: m.index, end: re.lastIndex });
      }
      if (!lines.length || /[\r\n]$/.test(text)) lines.push({ text: "", eol: "", start: text.length, end: text.length });
      return lines;
    }
    function escaped(text, index) {
      let count = 0;
      while (index > 0 && text[--index] === "\\") count++;
      return count % 2 === 1;
    }
    function splitPipes(line) {
      const cells = [];
      let start = 0;
      for (let i = 0; i < line.length; i++) {
        if (line[i] === "|" && !escaped(line, i)) {
          cells.push(line.slice(start, i));
          start = i + 1;
        }
      }
      cells.push(line.slice(start));
      if (!cells[0].trim()) cells.shift();
      if (cells.length && !cells[cells.length - 1].trim()) cells.pop();
      return cells;
    }
    function tableCellRange(text, anchor, row, column) {
      const data = classify(text);
      let line = data.lines.findIndex((l) => anchor >= l.start && (anchor < l.end || l.start === l.end && anchor === l.start));
      if (line < 0 || !data.table[line]) return null;
      while (line > 0 && data.table[line - 1]) line--;
      const sourceLine = line + (row === 0 ? 0 : row + 1);
      if (!data.table[sourceLine]) return null;
      const raw = data.lines[sourceLine], cells = [];
      let start = 0;
      for (let i = 0; i < raw.text.length; i++) if (raw.text[i] === "|" && !escaped(raw.text, i)) {
        cells.push({ from: start, to: i, text: raw.text.slice(start, i) });
        start = i + 1;
      }
      cells.push({ from: start, to: raw.text.length, text: raw.text.slice(start) });
      if (!cells[0].text.trim()) cells.shift();
      if (cells.length && !cells.at(-1).text.trim()) cells.pop();
      const cell = cells[column];
      return cell ? { from: raw.start + cell.from, to: raw.start + cell.to, line: sourceLine, count: cells.length } : null;
    }
    function isTableRule(line) {
      const cells = splitPipes(line);
      return cells.length > 0 && /\|/.test(line) && cells.every((c) => /^\s*:?-{3,}:?\s*$/.test(c));
    }
    function listItem(line) {
      const m = /^( *)([-+*]|\d+[.)])\s+(.*)$/.exec(line);
      return m ? { indent: m[1].length, content: m[3] } : null;
    }
    function interruptsParagraph(line) {
      return /^ {0,3}#{1,6}(?:\s|$)/.test(line) || /^ {0,3}(?:`{3,}|~{3,}|\$\$)/.test(line) || /^ {0,3}(?:([-*_])(?:\s*\1){2,})\s*$/.test(line) || /^ {0,3}(?:[-+*]|1[.)])\s+\S/.test(line) || /^ {0,3}<(?:!--|\?|!\[CDATA\[|![A-Z]|\/?(?:div|table|pre|script|style|details|section|figure|iframe)\b)/.test(line);
    }
    function classify(text, { splitLazyListLines = false } = {}) {
      const lines = linesOf(text);
      const kinds = Array(lines.length).fill("prose");
      const table = Array(lines.length).fill(false);
      const opaque = Array(lines.length).fill(false);
      const quotes = Array(lines.length).fill(false);
      const quoteBlanks = Array(lines.length).fill(false);
      const continuations = Array(lines.length).fill(false);
      const indentedCode = Array(lines.length).fill(false);
      let fence = null, yaml = false, comment = false, html = false, math = false;
      let quote = false, quoteCanLazy = false, list = false, lastListIndent = 0, listContentIndent = 2, reference = false;
      for (let i = 0; i < lines.length; i++) {
        const s = lines[i].text;
        if (quote && !/^\s*>/.test(s) && interruptsParagraph(s)) quote = false;
        if (i === 0 && /^\uFEFF?---\s*$/.test(s)) yaml = true;
        if (yaml) {
          kinds[i] = "protected";
          opaque[i] = true;
          if (i > 0 && /^(---|\.\.\.)\s*$/.test(s)) yaml = false;
          continue;
        }
        if (fence) {
          kinds[i] = "protected";
          opaque[i] = true;
          if (new RegExp("^\\s*" + fence.char + "{" + fence.length + ",}\\s*$").test(s)) fence = null;
          continue;
        }
        const fm = /^\s*(`{3,}|~{3,})/.exec(s);
        if (fm) {
          fence = { char: fm[1][0], length: fm[1].length };
          kinds[i] = "protected";
          opaque[i] = true;
          continue;
        }
        if (comment || /<!--|%%/.test(s)) {
          kinds[i] = "protected";
          opaque[i] = true;
          if (/<!--/.test(s) && !/-->/.test(s)) comment = "-->";
          else if (/%%/.test(s) && s.split("%%").length === 2) comment = comment ? false : "%%";
          else if (comment && s.includes(comment)) comment = false;
          continue;
        }
        if (/^\s*\$\$/.test(s) || math) {
          kinds[i] = "protected";
          opaque[i] = true;
          if (/^\s*\$\$/.test(s)) math = math ? false : s.trim() === "$$";
          continue;
        }
        if (html || /^\s*<(?:div|table|pre|script|style|details|section|figure|iframe)\b/i.test(s)) {
          kinds[i] = "protected";
          opaque[i] = true;
          if (!s.trim()) html = false;
          else html = !/<\/(?:div|table|pre|script|style|details|section|figure|iframe)>/i.test(s);
          continue;
        }
        if (!s.trim()) {
          kinds[i] = "blank";
          quote = false;
          reference = false;
          continue;
        }
        if (/^\s*>/.test(s)) {
          kinds[i] = "protected";
          quotes[i] = true;
          quote = true;
          list = false;
          const content = s.replace(/^(?:\s*>\s?)+/, "");
          quoteBlanks[i] = !content.trim();
          quoteCanLazy = !!content.trim() && !interruptsParagraph(content);
          if (listItem(content)?.content.trim()) quoteCanLazy = true;
          continue;
        }
        if (quote && quoteCanLazy) {
          kinds[i] = "protected";
          quotes[i] = true;
          continue;
        }
        quote = false;
        if (/^\s*\[[^\]]+\]:/.test(s)) {
          kinds[i] = "protected";
          opaque[i] = true;
          reference = true;
          continue;
        }
        if (reference && /^( {2,}|\t)/.test(s)) {
          kinds[i] = "protected";
          opaque[i] = true;
          continue;
        }
        reference = false;
        if (/^ {0,3}(?:([-*_])(?:\s*\1){2,})\s*$/.test(s)) {
          kinds[i] = "protected";
          list = false;
          continue;
        }
        const li = listItem(s);
        if (li) {
          kinds[i] = "list";
          list = true;
          lastListIndent = li.indent;
          listContentIndent = s.match(/^ *(?:[-+*]|\d+[.)])\s+/)[0].length;
          continue;
        }
        if (/^( {2,}|\t)/.test(s)) {
          const indent = s.match(/^\s*/)[0].replace(/\t/g, "    ").length;
          if (list && indent >= listContentIndent) {
            kinds[i] = "protected";
            opaque[i] = false;
            continuations[i] = indent < listContentIndent + 4 && !interruptsParagraph(s.trimStart()) && !/^\s*[<>!\[]/.test(s);
            continue;
          }
          if (indent >= 4 && !(i > 0 && kinds[i - 1] === "prose" && lines[i - 1].text.trim())) {
            kinds[i] = "protected";
            opaque[i] = true;
            indentedCode[i] = true;
            list = false;
            continue;
          }
          list = false;
        }
        if (list && i > 0 && lines[i - 1].text.trim() && !interruptsParagraph(s) && (!splitLazyListLines || lastListIndent > 0 || /(?: {2,}|\\)$/.test(lines[i - 1].text))) {
          kinds[i] = "protected";
          continuations[i] = true;
          continue;
        }
        list = false;
        if (/^ {0,3}#{1,6}(?:\s|$)/.test(s)) {
          kinds[i] = "heading";
          continue;
        }
        if (/^\s*(?:-{3,}|\*{3,}|_{3,})\s*$/.test(s)) {
          kinds[i] = "protected";
          continue;
        }
        if (/^\s*(?:=+|-+)\s*$/.test(s) && i > 0) {
          kinds[i] = kinds[i - 1] = "protected";
          continue;
        }
        if (/^\s*!\[/.test(s)) {
          kinds[i] = "image";
          continue;
        }
        if (/\[[^\]]*$/.test(s) || /^\s*[<>]/.test(s)) kinds[i] = "protected";
      }
      for (const regex of [/(`+)([\s\S]*?)\1/g, /(\*\*|__|~~)([\s\S]*?)\1/g, /<(span|mark|u)\b[^>]*>[\s\S]*?<\/\1>/gi, /\[[^\]]*\n[^\]]*\](?:\([^)]*\)|\[[^\]]*\])/g]) {
        let match;
        while (match = regex.exec(text)) if (/[\r\n]/.test(match[0])) {
          for (let i = 0; i < lines.length; i++) if (lines[i].start < regex.lastIndex && lines[i].end > match.index) {
            kinds[i] = "protected";
            continuations[i] = false;
            opaque[i] = true;
          }
        }
      }
      const tableContent = (s) => s.replace(/^\s*(?:>\s*)+/, "");
      for (let i = 1; i < lines.length; i++) {
        if (!opaque[i] && !opaque[i - 1] && isTableRule(tableContent(lines[i].text)) && splitPipes(tableContent(lines[i - 1].text)).length > 0) {
          let j = i - 1;
          while (j < lines.length && !opaque[j] && tableContent(lines[j].text).trim() && /\|/.test(lines[j].text)) {
            table[j] = true;
            kinds[j] = "table";
            j++;
          }
          i = j - 1;
        }
      }
      for (let i = 1; i < lines.length - 1; i++) if (kinds[i] === "blank" && indentedCode[i - 1]) {
        let j = i;
        while (j < lines.length && kinds[j] === "blank") j++;
        if (indentedCode[j]) for (let k = i; k < j; k++) {
          indentedCode[k] = true;
          kinds[k] = "protected";
        }
      }
      return { lines, kinds, table, quotes, quoteBlanks, continuations, indentedCode };
    }
    function formatNote2(text, { splitProseLines = true, looseLists = true, splitIndentedListParagraphs = false } = {}) {
      const { lines, kinds, quotes, continuations } = classify(text, { splitLazyListLines: splitProseLines });
      const eol = /\r\n/.test(text) ? "\r\n" : "\n";
      const insertBefore = /* @__PURE__ */ new Set();
      for (let i = 1; i < lines.length; i++) {
        const a = kinds[i - 1], b = kinds[i];
        if (a === "blank" || b === "blank") continue;
        if (continuations[i - 1] && ["prose", "heading", "image", "table"].includes(b) && /^\S/.test(lines[i].text)) insertBefore.add(i);
        if (splitIndentedListParagraphs && continuations[i] && /^( {2,}|\t)\S/.test(lines[i].text) && (a === "list" || continuations[i - 1]) && !/(?: {2,}|\\)$/.test(lines[i - 1].text) && !/(?: {2,}|\\)$/.test(lines[i].text)) insertBefore.add(i);
        if (quotes[i] && !quotes[i - 1] && /^>/.test(lines[i].text) && ["prose", "heading", "image", "table"].includes(a)) insertBefore.add(i);
        if (quotes[i - 1] && !quotes[i] && /^>/.test(lines[i - 1].text) && ["prose", "heading", "image", "table", "list"].includes(b) && /^\S/.test(lines[i].text)) insertBefore.add(i);
        const topA = listItem(lines[i - 1].text), topB = listItem(lines[i].text);
        if (looseLists && b === "list" && topB.indent === 0) {
          let j = i - 1;
          while (j >= 0 && lines[j].text.trim() && !listItem(lines[j].text) && /^( {2,}|\t)/.test(lines[j].text)) j--;
          if (topA && topA.indent === 0 || j >= 0 && kinds[j] === "list") insertBefore.add(i);
        }
        if (["prose", "heading", "image", "table"].includes(a) && b === "list" && topB.indent === 0) insertBefore.add(i);
        if (a === "list" && topA?.indent === 0 && ["prose", "heading", "image", "table"].includes(b)) insertBefore.add(i);
        if (a === "table" && b !== "table" && ["prose", "heading", "image"].includes(b)) insertBefore.add(i);
        if (b === "table" && a !== "table" && ["prose", "heading", "image"].includes(a)) insertBefore.add(i);
        if (["prose", "heading", "image"].includes(a) && ["prose", "heading", "image"].includes(b)) {
          if (a !== "prose" || b !== "prose" || splitProseLines && !/(?: {2,}|\\)$/.test(lines[i - 1].text)) insertBefore.add(i);
        }
      }
      const output = lines.map((line, i) => (insertBefore.has(i) ? eol : "") + line.text + line.eol).join("");
      return { text: output, inserted: insertBefore.size, protectedLines: kinds.filter((k) => k === "protected" || k === "table").length };
    }
    function excludedRanges(text, data) {
      const ranges = [];
      let yaml = false, fence = null, comment = false, list = false;
      data.lines.forEach((line, i) => {
        const s = line.text, stripped = s.replace(/^\s*>\s?/, "");
        if (i === 0 && /^\uFEFF?---\s*$/.test(s)) yaml = true;
        if (yaml) {
          ranges.push([line.start, line.end]);
          if (i > 0 && /^(---|\.\.\.)\s*$/.test(s)) yaml = false;
          return;
        }
        if (fence) {
          ranges.push([line.start, line.end]);
          if (new RegExp("^\\s*" + fence.char + "{" + fence.length + ",}\\s*$").test(stripped)) fence = null;
          return;
        }
        const m2 = /^\s*(`{3,}|~{3,})/.exec(stripped);
        if (m2) {
          fence = { char: m2[1][0], length: m2[1].length };
          ranges.push([line.start, line.end]);
          return;
        }
        if (comment || /<!--|%%/.test(s)) {
          ranges.push([line.start, line.end]);
          if (comment && s.includes(comment)) comment = false;
          else if (s.includes("<!--") && !s.includes("-->")) comment = "-->";
          else if (s.split("%%").length === 2) comment = "%%";
          return;
        }
        if (listItem(s)) list = true;
        if (!list && /^( {4}|\t)/.test(s)) ranges.push([line.start, line.end]);
        if (s.trim() && !/^\s/.test(s) && !listItem(s) && !/^>/.test(s)) list = false;
      });
      const inline = /(`+)([^]*?)\1/g;
      let m;
      while (m = inline.exec(text)) ranges.push([m.index, inline.lastIndex]);
      return ranges.sort((a, b) => a[0] - b[0]);
    }
    function closeBracket(text, start, close) {
      const open = close === "]" ? "[" : "(";
      let depth = 1;
      for (let i = start; i < text.length; i++) {
        if (escaped(text, i)) continue;
        if (text[i] === open) depth++;
        if (text[i] === close && --depth === 0) return i;
        if (text[i] === "\n" && close === "]") return -1;
      }
      return -1;
    }
    function wikiParts(content) {
      return content.split(/\\?\|/);
    }
    function scanImages2(text) {
      const data = classify(text);
      const ranges = excludedRanges(text, data);
      const references = /* @__PURE__ */ new Map();
      for (const line of data.lines) {
        const m = /^\s*\[([^\]]+)\]:\s*(?:<([^>]+)>|(\S+))/.exec(line.text);
        if (m) references.set(m[1].toLowerCase(), m[2] || m[3]);
      }
      const tokens = [];
      let rangeIndex = 0, lineIndex = 0;
      for (let i = 0; i < text.length; i++) {
        while (rangeIndex < ranges.length && ranges[rangeIndex][1] <= i) rangeIndex++;
        if (rangeIndex < ranges.length && ranges[rangeIndex][0] <= i) {
          i = ranges[rangeIndex][1] - 1;
          continue;
        }
        if (text[i] !== "!" || text[i + 1] !== "[" || escaped(text, i)) continue;
        while (lineIndex + 1 < data.lines.length && data.lines[lineIndex + 1].start <= i) lineIndex++;
        const base = { start: i, line: lineIndex, inTable: data.table[lineIndex] };
        if (text[i + 2] === "[") {
          let end2 = text.indexOf("]]", i + 3);
          if (end2 < 0 || text.slice(i, end2).includes("\n")) continue;
          end2 += 2;
          const content = text.slice(i + 3, end2 - 2);
          const parts = wikiParts(content);
          tokens.push({ ...base, end: end2, raw: text.slice(i, end2), type: "wiki", parts, target: parts[0], alt: parts.slice(1).join("|") });
          i = end2 - 1;
          continue;
        }
        const altEnd = closeBracket(text, i + 2, "]");
        if (altEnd < 0) continue;
        const alt = text.slice(i + 2, altEnd);
        let end, target, type;
        if (text[altEnd + 1] === "(") {
          let cursor = altEnd + 2;
          while (/\s/.test(text[cursor] || "") && cursor < text.length) cursor++;
          if (text[cursor] === "<") {
            const angleEnd = text.indexOf(">", cursor + 1);
            if (angleEnd < 0) continue;
            target = text.slice(cursor + 1, angleEnd);
            end = closeBracket(text, altEnd + 2, ")");
          } else {
            end = closeBracket(text, altEnd + 2, ")");
            const inside = end >= 0 ? text.slice(cursor, end) : "";
            target = inside.replace(/\s+["'][^]*$/, "");
          }
          if (end < 0) continue;
          end++;
          type = "markdown";
        } else if (text[altEnd + 1] === "[") {
          const refEnd = closeBracket(text, altEnd + 2, "]");
          if (refEnd < 0) continue;
          const ref = text.slice(altEnd + 2, refEnd) || alt;
          target = references.get(ref.toLowerCase());
          if (!target) continue;
          end = refEnd + 1;
          type = "reference";
        } else continue;
        tokens.push({ ...base, end, raw: text.slice(i, end), type, target, alt, altEnd: altEnd - i });
        i = end - 1;
      }
      return tokens;
    }
    function isExcalidraw2(token) {
      return !!token.isDrawing || /\.excalidraw(?:\.md)?(?:#|$)/i.test(token.target);
    }
    function isImageTarget2(target) {
      return /\.(?:png|jpe?g|gif|webp|svg|bmp|avif|heic|tiff?)(?:[?#]|$)/i.test(target) || /^(?:https?:|data:image\/)/i.test(target);
    }
    function relativeTarget(filePath, notePath) {
      const base = notePath.split("/").slice(0, -1), dest = filePath.split("/");
      while (base.length && dest.length && base[0] === dest[0]) {
        base.shift();
        dest.shift();
      }
      return [...base.map(() => ".."), ...dest].map((p) => encodeURIComponent(p)).join("/");
    }
    function resizedToken(token, width, height = null, options = {}) {
      width = Math.round(width);
      if (!Number.isFinite(width) || width < 24 || width > 8192) throw new Error("\u56FE\u7247\u5BBD\u5EA6\u5FC5\u987B\u5728 24\u20138192 px \u4E4B\u95F4");
      if (height !== null) {
        height = Math.round(height);
        if (!Number.isFinite(height) || height < 24 || height > 8192) throw new Error("\u56FE\u7247\u9AD8\u5EA6\u5FC5\u987B\u5728 24\u20138192 px \u4E4B\u95F4");
      }
      const size = height === null ? String(width) : `${width}x${height}`;
      const pipe = token.inTable ? "\\|" : "|";
      if (token.type === "wiki") {
        const parts = [...token.parts];
        const sizeIndex = parts.findIndex((p, i) => i > 0 && /^\d+(?:x\d+)?$/.test(p.trim()));
        if (sizeIndex >= 0) parts[sizeIndex] = size;
        else if (parts.length === 1) parts.push(size);
        else if (isExcalidraw2(token)) parts.splice(1, 0, size);
        else {
          if (!options.resolvedPath || !options.notePath) throw new Error("\u65E0\u6CD5\u89E3\u6790\u5E26\u522B\u540D\u7684\u56FE\u7247\u8DEF\u5F84\uFF1B\u8BF7\u4F7F\u7528\u56FE\u7247\u5C3A\u5BF8\u547D\u4EE4\u68C0\u67E5");
          const alt2 = parts.slice(1).join("|").replace(/\\?\|/g, token.inTable ? "\\|" : "|").replace(/(?<!\\)\]/g, "\\]");
          const fragment = token.target.includes("#") ? "#" + token.target.split("#").slice(1).join("#") : "";
          return `![${alt2}${pipe}${size}](<${relativeTarget(options.resolvedPath, options.notePath)}${fragment}>)`;
        }
        return `![[${parts.join(pipe)}]]`;
      }
      let alt = token.alt.replace(/\\?\|\d+(?:x\d+)?$/, "");
      if (/^\d+(?:x\d+)?$/.test(alt)) alt = "";
      if (token.inTable) alt = alt.replace(/(?<!\\)\|/g, "\\|");
      const suffix = token.raw.slice(token.altEnd + 1);
      const fixedSuffix = token.type === "reference" && suffix === "[]" ? `[${token.alt}]` : suffix;
      return `![${alt}${pipe}${size}]${fixedSuffix}`;
    }
    function sameDocumentPatch(text, token, replacement) {
      if (text.slice(token.start, token.end) !== token.raw) throw new Error("\u7B14\u8BB0\u5DF2\u53D8\u5316\uFF0C\u8BF7\u91CD\u65B0\u70B9\u51FB\u56FE\u7247\u540E\u8C03\u6574");
      const before = text.slice(0, token.start), after = text.slice(token.end);
      if (token.inTable) {
        const lineStart = before.lastIndexOf("\n") + 1;
        const next = text.indexOf("\n", token.end);
        const oldLine = text.slice(lineStart, next < 0 ? text.length : next);
        const newLine = before.slice(lineStart) + replacement + after.split("\n")[0];
        if (splitPipes(oldLine).length !== splitPipes(newLine).length) throw new Error("\u5C3A\u5BF8\u5199\u56DE\u4F1A\u6539\u53D8\u8868\u683C\u5217\u6570\uFF0C\u5DF2\u53D6\u6D88");
      }
      return before + replacement + after;
    }
    function dragSize(initial, dx, dy, corner, free, maxWidth = 4096) {
      const sx = corner.includes("w") ? -1 : 1, sy = corner.includes("n") ? -1 : 1;
      const rawW = initial.width + dx * sx, rawH = initial.height + dy * sy;
      const max = Math.min(8192, Math.max(24, maxWidth));
      const clamp = (n) => Math.max(24, Math.min(max, n));
      if (free) return { width: Math.round(clamp(rawW)), height: Math.round(Math.max(24, Math.min(8192, rawH))) };
      const ratio = initial.width / initial.height;
      let w = Math.abs(dx / initial.width) >= Math.abs(dy / initial.height) ? rawW : rawH * ratio;
      w = Math.max(24, 24 * ratio, Math.min(max, 8192 * ratio, w));
      return { width: Math.round(w), height: Math.round(w / ratio) };
    }
    module2.exports = { linesOf, splitPipes, classify, formatNote: formatNote2, scanImages: scanImages2, resizedToken, sameDocumentPatch, dragSize, isExcalidraw: isExcalidraw2, isImageTarget: isImageTarget2, relativeTarget, tableCellRange };
  }
});

// src/text-style.js
var require_text_style = __commonJS({
  "src/text-style.js"(exports2, module2) {
    var HEX2 = /^#[0-9a-f]{6}$/i;
    var tag = {
      color: { open: (color) => `<span style="color: ${color};">`, close: "</span>", pattern: /^<span style="color:\s*(#[0-9a-f]{6});?">([\s\S]*)<\/span>$/i },
      highlight: { open: (color, foreground = "#202020") => `<mark style="background-color: ${color}; color: ${foreground};">`, close: "</mark>", pattern: /^<mark style="background-color:\s*(#[0-9a-f]{6});(?: color:\s*#[0-9a-f]{6};)?">([\s\S]*)<\/mark>$/i },
      underline: { open: () => "<u>", close: "</u>", pattern: /^<u>([\s\S]*)<\/u>$/i }
    };
    function stylePatch(text, start, end, kind, value) {
      if (start === end) throw new Error("\u8BF7\u5148\u9009\u4E2D\u6587\u5B57");
      if (!tag[kind] && kind !== "clear") throw new Error("\u672A\u77E5\u6837\u5F0F");
      if (["color", "highlight"].includes(kind) && !HEX2.test(value)) throw new Error("\u989C\u8272\u5FC5\u987B\u662F #RRGGBB");
      const selected = text.slice(start, end);
      if (/[\r\n]/.test(selected)) throw new Error("\u6587\u5B57\u6837\u5F0F\u8BF7\u5728\u4E00\u4E2A\u6BB5\u843D\u5185\u9009\u53D6\uFF1B\u4E0D\u8DE8\u6BB5\u843D\u6216\u8868\u683C\u884C\u5E94\u7528 HTML");
      let left = start, right = end, inner = selected;
      const unwrap = (k) => {
        const t = tag[k];
        const whole = inner.match(t.pattern);
        const wholeInner = whole?.[k === "underline" ? 1 : 2];
        if (whole && !wholeInner.includes(t.close)) {
          inner = wholeInner;
          return true;
        }
        const before = text.slice(0, left), after = text.slice(right);
        const regex = k === "color" ? /<span style="color:\s*#[0-9a-f]{6};?">$/i : k === "highlight" ? /<mark style="background-color:\s*#[0-9a-f]{6};(?: color:\s*#[0-9a-f]{6};)?">$/i : /<u>$/i;
        const m = before.match(regex);
        if (m && after.startsWith(t.close) && !inner.includes(t.close)) {
          left -= m[0].length;
          right += t.close.length;
          return true;
        }
        return false;
      };
      if (kind === "clear") {
        let changed;
        do {
          changed = false;
          for (const k of Object.keys(tag)) changed = unwrap(k) || changed;
        } while (changed);
        return { from: left, to: right, text: inner, selectFrom: left, selectTo: left + inner.length };
      }
      const existing = unwrap(kind);
      if (kind === "underline" && existing) return { from: left, to: right, text: inner, selectFrom: left, selectTo: left + inner.length };
      const ancestorColor = text.slice(0, left).match(/<span style="color:\s*(#[0-9a-f]{6});?">(?:<u>|<mark style="background-color:\s*#[0-9a-f]{6};(?: color:\s*#[0-9a-f]{6};)?">)*$/i)?.[1];
      const open = tag[kind].open(value, ancestorColor), close = tag[kind].close;
      return { from: left, to: right, text: open + inner + close, selectFrom: left + open.length, selectTo: left + open.length + inner.length };
    }
    function captureSelection2(editor, file) {
      const text = editor.getValue();
      const start = editor.posToOffset(editor.getCursor("from"));
      const end = editor.posToOffset(editor.getCursor("to"));
      if (start === end) throw new Error("\u8BF7\u5148\u9009\u4E2D\u6587\u5B57");
      return { editor, file, text, start, end };
    }
    function commitStyle2(snapshot, kind, value) {
      const { editor, text, start, end } = snapshot;
      if (editor.getValue() !== text || snapshot.info && snapshot.info.file?.path !== snapshot.file?.path) throw new Error("\u7B14\u8BB0\u5DF2\u53D8\u5316\uFF0C\u8BF7\u91CD\u65B0\u9009\u62E9\u6587\u5B57");
      const p = stylePatch(text, start, end, kind, value);
      const next = text.slice(0, p.from) + p.text + text.slice(p.to);
      const pos = (offset) => {
        const parts = next.slice(0, offset).split("\n");
        return { line: parts.length - 1, ch: parts.at(-1).length };
      };
      editor.transaction({ changes: [{ from: editor.offsetToPos(p.from), to: editor.offsetToPos(p.to), text: p.text }], selection: { from: pos(p.selectFrom), to: pos(p.selectTo) } });
      editor.focus();
    }
    module2.exports = { stylePatch, captureSelection: captureSelection2, commitStyle: commitStyle2, HEX: HEX2 };
  }
});

// src/layout.js
var require_layout = __commonJS({
  "src/layout.js"(exports2, module2) {
    var { ViewPlugin, Decoration, keymap } = require("@codemirror/view");
    var { RangeSetBuilder, Prec, EditorState } = require("@codemirror/state");
    var { editorInfoField } = require("obsidian");
    var { classify } = require_markdown();
    function layoutExtension2(plugin) {
      const decorations = ViewPlugin.fromClass(class {
        constructor(view) {
          this.view = view;
          plugin.cmViews.add(view);
          plugin.bindDocument(view.dom.ownerDocument);
          this.decorations = this.build();
        }
        update(update) {
          if (update.docChanged || update.viewportChanged || update.transactions.length) this.decorations = this.build();
        }
        destroy() {
          plugin.cmViews.delete(this.view);
        }
        build() {
          const builder = new RangeSetBuilder();
          if (!plugin.settings.layoutEnabled) return builder.finish();
          const view = this.view;
          const info = view.state.field(editorInfoField, false);
          if (info?.getMode?.() === "source" && info?.getState?.()?.source === true) return builder.finish();
          const doc = view.state.doc;
          const { kinds, lines, continuations, quotes, quoteBlanks, indentedCode } = classify(doc.toString());
          const tabRows = /* @__PURE__ */ new Set();
          if (plugin.settings.tabKnowledgeLines) {
            const keys = tabKnowledgeKeys(doc.toString());
            for (let i = 0; i < lines.length; i++) if (indentedCode[i] && (i === 0 || !indentedCode[i - 1])) {
              let j = i;
              while (indentedCode[j]) j++;
              const key = lines.slice(i, j).map((l) => l.text.replace(/^(?: {0,3}\t| {4})/, "")).join("\n");
              if (keys.has(key)) for (let k = i; k < j; k++) tabRows.add(k);
              i = j - 1;
            }
          }
          let previous = -1;
          for (const range of view.visibleRanges) {
            const first = doc.lineAt(range.from).number, last = doc.lineAt(range.to).number;
            for (let n = first; n <= last; n++) {
              const line = doc.line(n), kind = kinds[n - 1];
              if (line.from <= previous) continue;
              previous = line.from;
              if (kind === "table" || kind === "protected" && !continuations[n - 1] && !quotes[n - 1] && !indentedCode[n - 1]) continue;
              const cls = kind === "blank" ? "tet-gap" : kind === "heading" ? "tet-heading" : kind === "list" ? "tet-list-line" : kind === "image" ? "tet-image-line" : "tet-prose";
              const attrs = { class: cls };
              if (kind === "prose") {
                if (kinds[n - 2] !== "prose") attrs.class += " tet-block-start";
                if (kinds[n] !== "prose") attrs.class += " tet-block-end";
              }
              if (kind === "list") {
                attrs.class += " tet-block-start";
                if (!continuations[n]) attrs.class += " tet-block-end";
              }
              if (continuations[n - 1]) {
                attrs.class += " tet-list-continuation";
                if (kinds[n - 2] === "blank") attrs.class += " tet-block-start";
                if (!continuations[n]) attrs.class += " tet-block-end";
              }
              if (quotes[n - 1]) {
                attrs.class = quoteBlanks[n - 1] ? "tet-quote-line tet-quote-gap" : "tet-quote-line";
                if (!quoteBlanks[n - 1]) {
                  if (!quotes[n - 2] || quoteBlanks[n - 2]) attrs.class += " tet-block-start";
                  if (!quotes[n] || quoteBlanks[n]) attrs.class += " tet-block-end";
                }
              }
              if (indentedCode[n - 1]) {
                attrs.class = "tet-code-line";
                const tabKnowledge = tabRows.has(n - 1);
                if (tabKnowledge) attrs.class = lines[n - 1].text.trim() ? "tet-code-line tet-tab-knowledge-line tet-block-start tet-block-end" : "tet-gap tet-tab-gap";
                else {
                  if (!indentedCode[n - 2]) attrs.class += " tet-block-start";
                  if (!indentedCode[n]) attrs.class += " tet-block-end";
                }
              }
              if (kind === "heading") attrs.class += ` tet-h${Math.min(6, (lines[n - 1].text.match(/^\s*(#+)/)?.[1] || "#").length)}`;
              builder.add(line.from, line.from, Decoration.line({ attributes: attrs }));
            }
          }
          return builder.finish();
        }
      }, { decorations: (value) => value.decorations });
      return [decorations, Prec.highest(keymap.of([{ key: "Enter", run: (view) => {
        if (!plugin.settings.paragraphEnter || !plugin.settings.splitProseLines || view.state.selection.ranges.length !== 1 || view.state.facet(EditorState.readOnly)) return false;
        const info = view.state.field(editorInfoField, false);
        if (!info?.file || info?.getState?.()?.source === true || info.file.path.match(/\.excalidraw(?:\.md)?$/i)) return false;
        const selection = view.state.selection.main, line = view.state.doc.lineAt(selection.head);
        if (!selection.empty || selection.head !== line.to || !line.text.trim() || /(?: {2,}|\\)$/.test(line.text)) return false;
        const data = classify(view.state.doc.toString());
        if (data.kinds[line.number - 1] !== "prose") return false;
        const tail = view.state.doc.sliceString(line.to);
        if (!tail.trim()) {
          const breaks = (tail.match(/\n/g) || []).length;
          const insert = "\n".repeat(Math.max(0, 2 - breaks));
          view.dispatch({ changes: insert ? { from: line.to, insert } : void 0, selection: { anchor: line.to + 2 }, scrollIntoView: true, userEvent: "input" });
        } else {
          const next = view.state.doc.line(line.number + 1).text;
          const insert = next.trim() ? "\n\n\n" : "\n\n";
          view.dispatch({ changes: { from: line.to, insert }, selection: { anchor: line.to + 2 }, scrollIntoView: true, userEvent: "input" });
        }
        return true;
      } }]))];
    }
    function isTabKnowledgeLine(text) {
      return /^ {0,3}\t\S|^ {0,3}\t\s+\S/.test(text);
    }
    var tabContexts = /* @__PURE__ */ new WeakMap();
    function normalizedCode(text) {
      return text.replace(/\r\n/g, "\n").replace(/\n$/, "");
    }
    function tabKnowledgeKeys(source) {
      const data = classify(source), keys = /* @__PURE__ */ new Set(), excluded = /* @__PURE__ */ new Set();
      for (let i = 0; i < data.lines.length; i++) if (data.indentedCode[i] && (i === 0 || !data.indentedCode[i - 1])) {
        let j = i;
        while (data.indentedCode[j]) j++;
        const rows = data.lines.slice(i, j).map((l) => l.text);
        const key = rows.map((s) => s.replace(/^(?: {0,3}\t| {4})/, "")).join("\n");
        if (rows.filter((s) => s.trim()).every(isTabKnowledgeLine)) keys.add(key);
        else excluded.add(key);
        i = j - 1;
      }
      let fence = null, body = [];
      for (const line of data.lines) {
        const m = /^ {0,3}(`{3,}|~{3,})/.exec(line.text);
        if (!fence && m) {
          fence = m[1];
          body = [];
          continue;
        }
        if (fence) {
          if (new RegExp("^ {0,3}" + fence[0] + "{" + fence.length + ",}\\s*$").test(line.text)) {
            excluded.add(body.join("\n"));
            fence = null;
          } else body.push(line.text);
        }
      }
      for (const key of excluded) keys.delete(key);
      return keys;
    }
    function decorateTabKnowledge2(el, ctx, settings) {
      const blocks = [...el.matches?.("pre") ? [el] : [], ...el.querySelectorAll("pre")];
      for (const pre of blocks) {
        tabContexts.set(pre, ctx);
        if (!settings.layoutEnabled || !settings.tabKnowledgeLines) continue;
        if (pre.classList.contains("tet-tab-knowledge")) continue;
        const code = pre.querySelector("code");
        if (!code || [...code.classList].some((c) => c.startsWith("language-"))) continue;
        let info;
        try {
          info = ctx.getSectionInfo(pre);
        } catch {
          continue;
        }
        if (!info?.text || !tabKnowledgeKeys(info.text).has(normalizedCode(code.textContent))) continue;
        const text = code.textContent, rows = normalizedCode(text).split("\n");
        code.replaceChildren();
        rows.forEach((row, i) => {
          const span = code.ownerDocument.createElement("span");
          span.className = row.trim() ? "tet-tab-row" : "tet-tab-empty";
          span.textContent = row;
          code.appendChild(span);
          if (i < rows.length - 1 || text.endsWith("\n")) code.appendChild(code.ownerDocument.createTextNode("\n"));
        });
        pre.classList.add("tet-tab-knowledge");
        code.classList.add("tet-tab-code");
      }
    }
    function refreshTabKnowledge2(doc, settings) {
      for (const pre of doc.querySelectorAll("pre")) {
        if (pre.classList.contains("tet-tab-knowledge")) {
          const code = pre.querySelector("code");
          if (code) {
            code.textContent = code.textContent;
            code.classList.remove("tet-tab-code");
          }
          pre.classList.remove("tet-tab-knowledge");
        }
        const ctx = tabContexts.get(pre);
        if (ctx && settings) decorateTabKnowledge2(pre, ctx, settings);
      }
    }
    function applyLayout2(doc, settings) {
      doc.body.classList.toggle("tet-enabled", settings.layoutEnabled);
      const vars = {
        "--tet-line-height": settings.lineHeight,
        "--tet-block-padding": settings.blockPadding + "em",
        "--tet-h1": settings.headingH1 + "em",
        "--tet-h2": settings.headingH2 + "em",
        "--tet-h3": settings.headingH3 + "em",
        "--tet-h4": settings.headingH4 + "em",
        "--tet-list-indent": settings.listIndent + "em",
        "--tet-image-padding": settings.imagePadding + "em",
        "--tet-table-padding": settings.tablePadding + "em"
      };
      let style = doc.getElementById("tet-layout-vars");
      if (!style) {
        style = doc.createElement("style");
        style.id = "tet-layout-vars";
        doc.head.appendChild(style);
      }
      style.textContent = `:root { ${Object.entries(vars).map(([k, v]) => `${k}: ${v};`).join(" ")} }`;
    }
    module2.exports = { layoutExtension: layoutExtension2, applyLayout: applyLayout2, decorateTabKnowledge: decorateTabKnowledge2, refreshTabKnowledge: refreshTabKnowledge2, tabKnowledgeKeys };
  }
});

// src/image-resize.js
var require_image_resize = __commonJS({
  "src/image-resize.js"(exports2, module2) {
    var { Notice: Notice2, MarkdownView: MarkdownView2, editorInfoField } = require("obsidian");
    var { resizedToken, sameDocumentPatch, dragSize, isExcalidraw: isExcalidraw2, isImageTarget: isImageTarget2, tableCellRange } = require_markdown();
    function cleanTarget2(value) {
      try {
        value = decodeURIComponent(value);
      } catch (_) {
      }
      return value.replace(/\\([ ()])/g, "$1").replace(/\\?\|.*$/, "").replace(/^<|>$/g, "").split("#")[0].replace(/^\.\//, "");
    }
    function imageElement(target) {
      if (!target?.closest || target.closest(".tet-resize-overlay, .tet-modal")) return null;
      const embed = target.closest(".excalidraw-embedded-img[filesource]") || target.closest(".internal-embed") || target.closest(".excalidraw-embedded-img") || target.closest(".excalidraw-svg");
      if (embed && /\.excalidraw(?:\.md)?(?:#|$)/i.test(embed.getAttribute("src") || embed.getAttribute("data-src") || embed.getAttribute("filesource") || "")) {
        return { element: embed.querySelector("img,svg") || embed, embed };
      }
      if (embed && (embed.classList.contains("image-embed") || isImageTarget2(embed.getAttribute("src") || ""))) {
        const child = embed.querySelector("img");
        if (child) return { element: child, embed };
      }
      const image = target.closest("img");
      if (image && image.closest(".markdown-source-view, .markdown-preview-view, .markdown-rendered")) return { element: image, embed: embed || image };
      const svg = target.closest(".excalidraw-svg svg, svg.excalidraw-svg");
      return svg ? { element: svg, embed: embed || svg } : null;
    }
    var ImageResizeManager2 = class {
      constructor(plugin) {
        this.plugin = plugin;
        this.contexts = /* @__PURE__ */ new WeakMap();
        this.bindings = /* @__PURE__ */ new Map();
        this.session = null;
        this.resolveId = 0;
      }
      bind(doc) {
        if (this.bindings.has(doc)) return;
        const pointer = (e) => this.onSelect(e);
        const click = (e) => {
          if (this.blockClick && imageElement(e.target)) {
            e.preventDefault();
            e.stopPropagation();
            this.blockClick = false;
          }
        };
        const key = (e) => {
          if (e.key === "Escape") {
            this.resolveId++;
            this.close();
          }
        };
        const scroll = () => {
          if (this.session && !this.session.dragging) this.position();
        };
        doc.addEventListener("pointerdown", pointer, true);
        doc.addEventListener("click", click, true);
        doc.addEventListener("keydown", key, true);
        doc.addEventListener("scroll", scroll, true);
        doc.defaultView.addEventListener("resize", scroll);
        this.bindings.set(doc, () => {
          doc.removeEventListener("pointerdown", pointer, true);
          doc.removeEventListener("click", click, true);
          doc.removeEventListener("keydown", key, true);
          doc.removeEventListener("scroll", scroll, true);
          doc.defaultView.removeEventListener("resize", scroll);
        });
      }
      annotate(el, ctx) {
        this.contexts.set(el, ctx);
      }
      contextFor(element) {
        for (let node = element; node; node = node.parentElement) {
          if (this.contexts.has(node)) return { ctx: this.contexts.get(node), root: node };
        }
        return null;
      }
      findEditorView(element) {
        for (const view of this.plugin.cmViews) if (view.dom.contains(element)) return view;
        return null;
      }
      async locate(hit) {
        const cm = this.findEditorView(hit.element);
        const ctxInfo = this.contextFor(hit.element);
        let info = cm?.state.field(editorInfoField, false);
        if (!info?.file && !ctxInfo) {
          this.plugin.app.workspace.iterateAllLeaves((leaf) => {
            if (leaf.view instanceof MarkdownView2 && leaf.view.containerEl.contains(hit.element)) info = leaf.view;
          });
        }
        const sourcePath = ctxInfo?.ctx.sourcePath || info?.file?.path;
        const file = this.plugin.app.vault.getAbstractFileByPath(sourcePath || "");
        if (!file || file.extension !== "md") throw new Error("\u6CA1\u6709\u627E\u5230\u56FE\u7247\u6240\u5728\u7684 Markdown \u7B14\u8BB0");
        const editor = cm ? info?.editor : null;
        const text = editor ? editor.getValue() : await this.plugin.app.vault.read(file);
        const tokens = this.plugin.imageTokens(text, file.path);
        let candidates = tokens;
        let rangeStart = null, rangeEnd = null;
        const tableNode = hit.element.closest("table");
        const tableCell = hit.element.closest("td,th");
        if (cm) {
          let pos;
          try {
            pos = cm.posAtDOM(hit.embed);
          } catch (_) {
            try {
              pos = cm.posAtDOM(hit.element);
            } catch (_2) {
            }
          }
          if (Number.isInteger(pos)) {
            const line = cm.state.doc.lineAt(pos);
            const local = tokens.filter((t) => t.start >= line.from && t.start <= line.to);
            const covering = local.filter((t) => pos >= t.start && pos <= t.end);
            candidates = covering.length ? covering : local.length ? local : tokens;
            rangeStart = line.from;
            rangeEnd = line.to;
          }
          if (tableNode && tableCell) {
            let tableAnchor;
            try {
              tableAnchor = cm.posAtDOM(tableNode);
            } catch (_) {
            }
            const cellRange = Number.isInteger(tableAnchor) ? tableCellRange(text, tableAnchor, tableCell.parentElement.rowIndex, tableCell.cellIndex) : null;
            if (cellRange && cellRange.count === tableCell.parentElement.cells.length) {
              candidates = tokens.filter((t) => t.start >= cellRange.from && t.end <= cellRange.to);
            } else throw new Error("\u8868\u683C\u884C\u5217\u4E0E\u6E90\u7801\u5C1A\u672A\u540C\u6B65\uFF0C\u672A\u5199\u56DE\uFF1B\u8BF7\u91CD\u65B0\u70B9\u51FB\u56FE\u7247");
          }
        } else if (ctxInfo) {
          const section = ctxInfo.ctx.getSectionInfo(ctxInfo.root);
          if (section) candidates = tokens.filter((t) => t.line >= section.lineStart && t.line <= section.lineEnd);
        }
        const targetAttr = hit.embed.getAttribute("src") || hit.embed.getAttribute("data-src") || hit.embed.getAttribute("data-href") || hit.embed.getAttribute("filesource");
        const source = hit.element.getAttribute("src") || hit.element.getAttribute("href") || "";
        const alt = hit.element.getAttribute("alt") || "";
        const matches = candidates.filter((t) => {
          const cleaned = cleanTarget2(t.target);
          const resolved2 = this.plugin.app.metadataCache.getFirstLinkpathDest(cleaned, file.path);
          if (targetAttr && cleanTarget2(targetAttr) === cleaned) return true;
          if (resolved2 && cleanTarget2(targetAttr || "") === resolved2.path) return true;
          if (source && (cleanTarget2(source) === cleaned || resolved2 && cleanTarget2(source).includes(resolved2.path))) return true;
          if (alt && [cleaned, cleaned.split("/").at(-1), t.alt.replace(/\\?\|\d+(?:x\d+)?$/, "")].includes(alt)) return true;
          return false;
        });
        if (!matches.length) throw new Error("\u56FE\u7247\u4E0E\u6E90\u7801\u94FE\u63A5\u4E0D\u5339\u914D\uFF0C\u672A\u5199\u56DE\uFF1B\u8BF7\u4F7F\u7528\u201C\u8BBE\u7F6E\u5149\u6807\u5904\u56FE\u7247\u5C3A\u5BF8\u201D\u547D\u4EE4");
        candidates = matches;
        if (candidates.length > 1) {
          const root = cm && tableCell ? tableCell : ctxInfo?.root || hit.element.closest(".cm-line, .cm-embed-block, .markdown-preview-section");
          if (root) {
            const nodes = [...root.querySelectorAll("img, .excalidraw-svg svg, svg.excalidraw-svg")].filter((n) => !n.closest(".tet-resize-overlay"));
            const matchingNodes = nodes.filter((n) => {
              const parent = n.closest(".excalidraw-embedded-img[filesource],.internal-embed");
              const parentTarget = parent?.getAttribute("src") || parent?.getAttribute("filesource");
              return targetAttr && parentTarget === targetAttr || !!source && n.getAttribute("src") === source;
            });
            const index = matchingNodes.indexOf(hit.element);
            if (index >= 0 && matchingNodes.length === candidates.length) candidates = [candidates[index]];
          }
        }
        if (candidates.length !== 1) throw new Error("\u65E0\u6CD5\u552F\u4E00\u5B9A\u4F4D\u8FD9\u5F20\u56FE\u7247\uFF1B\u8BF7\u5C06\u5149\u6807\u653E\u5230\u5BF9\u5E94\u56FE\u7247\u8BED\u6CD5\u5185\uFF0C\u4F7F\u7528\u201C\u8BBE\u7F6E\u56FE\u7247\u5C3A\u5BF8\u201D\u547D\u4EE4");
        const token = candidates[0];
        const resolved = this.plugin.app.metadataCache.getFirstLinkpathDest(cleanTarget2(token.target), file.path);
        return { file, editor, info, text, token, resolvedPath: resolved?.path, notePath: file.path };
      }
      async onSelect(event) {
        if (!this.plugin.settings.imageResize || event.button !== 0) return;
        if (event.target.closest?.(".tet-resize-overlay")) return;
        if (event.altKey || event.ctrlKey || event.metaKey || event.shiftKey) return;
        const hit = imageElement(event.target);
        const id = ++this.resolveId;
        if (!hit) {
          this.close();
          return;
        }
        if (!this.findEditorView(hit.element) && !this.plugin.settings.readingResize) return;
        event.preventDefault();
        event.stopPropagation();
        this.blockClick = true;
        this.close();
        try {
          const source = await this.locate(hit);
          if (id !== this.resolveId || !hit.element.isConnected) return;
          if (isExcalidraw2(source.token) && !this.plugin.excalidrawAvailable()) throw new Error("\u8BF7\u542F\u7528 Excalidraw \u63D2\u4EF6\u540E\u7F29\u653E\u7ED8\u56FE\u5D4C\u5165");
          this.show(hit, source);
        } catch (error) {
          if (id === this.resolveId) new Notice2(error.message);
        }
      }
      show(hit, source) {
        const doc = hit.element.ownerDocument;
        const box = doc.createElement("div");
        box.className = "tet-resize-overlay";
        box.setAttribute("role", "group");
        box.setAttribute("aria-label", "\u56FE\u7247\u7F29\u653E\uFF1A\u62D6\u52A8\u56DB\u89D2\uFF0CAlt \u81EA\u7531\u5BBD\u9AD8\uFF0CEsc \u53D6\u6D88");
        const label = doc.createElement("div");
        label.className = "tet-resize-label";
        box.appendChild(label);
        this.session = { ...hit, source, box, label, dragging: false, cleanup: null };
        for (const corner of ["nw", "ne", "sw", "se"]) {
          const handle = doc.createElement("button");
          handle.className = `tet-resize-handle tet-${corner}`;
          handle.setAttribute("aria-label", `\u62D6\u52A8 ${corner} \u7F29\u653E\u56FE\u7247`);
          handle.title = "\u62D6\u52A8\u4FDD\u6301\u6BD4\u4F8B\uFF1B\u6309 Alt \u81EA\u7531\u8C03\u6574\u5BBD\u9AD8";
          handle.addEventListener("pointerdown", (event) => this.startDrag(event, corner));
          box.appendChild(handle);
        }
        doc.body.appendChild(box);
        this.position();
      }
      position(rect = null) {
        const s = this.session;
        if (!s) return;
        if (!s.element.isConnected) {
          this.close();
          return;
        }
        const r = rect || s.element.getBoundingClientRect();
        Object.assign(s.box.style, { left: r.left + "px", top: r.top + "px", width: r.width + "px", height: r.height + "px" });
        s.label.textContent = `${Math.round(r.width)} \xD7 ${Math.round(r.height)} \xB7 Alt \u81EA\u7531\u7F29\u653E`;
      }
      startDrag(event, corner) {
        const s = this.session;
        if (!s) return;
        event.preventDefault();
        event.stopPropagation();
        const initial = s.element.getBoundingClientRect(), doc = s.element.ownerDocument;
        const x = event.clientX, y = event.clientY;
        s.dragging = true;
        s.box.classList.add("tet-dragging");
        let dimensions = { width: initial.width, height: initial.height }, moved = false, free = false;
        const move = (e) => {
          if (e.pointerId !== event.pointerId) return;
          moved = moved || Math.abs(e.clientX - x) + Math.abs(e.clientY - y) > 3;
          free = e.altKey || this.plugin.settings.freeResize;
          dimensions = dragSize(initial, e.clientX - x, e.clientY - y, corner, free, this.plugin.settings.maxImageWidth);
          this.position({
            left: corner.includes("w") ? initial.right - dimensions.width : initial.left,
            top: corner.includes("n") ? initial.bottom - dimensions.height : initial.top,
            ...dimensions
          });
        };
        const cleanup = () => {
          doc.removeEventListener("pointermove", move, true);
          doc.removeEventListener("pointerup", end, true);
          doc.removeEventListener("pointercancel", cancel, true);
          doc.defaultView.removeEventListener("blur", cancel);
          s.cleanup = null;
          s.dragging = false;
        };
        const cancel = () => {
          cleanup();
          this.close();
        };
        const end = async (e) => {
          if (e.pointerId !== event.pointerId) return;
          cleanup();
          this.close();
          if (!moved) return;
          try {
            await this.commit(s.source, dimensions.width, free ? dimensions.height : null);
          } catch (error) {
            new Notice2(error.message, 6e3);
          }
        };
        s.cleanup = cleanup;
        doc.addEventListener("pointermove", move, true);
        doc.addEventListener("pointerup", end, true);
        doc.addEventListener("pointercancel", cancel, true);
        doc.defaultView.addEventListener("blur", cancel);
      }
      async commit(source, width, height) {
        const { file, editor, text, token } = source;
        const replacement = resizedToken(token, width, height, source);
        sameDocumentPatch(text, token, replacement);
        if (editor) {
          if (editor.getValue() !== text || source.info && source.info.file?.path !== file.path) throw new Error("\u62D6\u52A8\u671F\u95F4\u7B14\u8BB0\u5DF2\u53D8\u5316\uFF0C\u5DF2\u53D6\u6D88\u5199\u56DE\uFF1B\u8BF7\u91CD\u65B0\u70B9\u51FB\u56FE\u7247");
          editor.transaction({ changes: [{ from: editor.offsetToPos(token.start), to: editor.offsetToPos(token.end), text: replacement }] });
        } else {
          let openEditor;
          this.plugin.app.workspace.iterateAllLeaves((leaf) => {
            if (leaf.view instanceof MarkdownView2 && leaf.view.file?.path === file.path && leaf.view.getMode() === "source") openEditor = leaf.view.editor;
          });
          if (openEditor) {
            if (openEditor.getValue() !== text) throw new Error("\u53E6\u4E00\u7F16\u8F91\u7A97\u683C\u6709\u672A\u540C\u6B65\u66F4\u6539\uFF0C\u5DF2\u53D6\u6D88\u5199\u56DE");
            openEditor.transaction({ changes: [{ from: openEditor.offsetToPos(token.start), to: openEditor.offsetToPos(token.end), text: replacement }] });
          } else {
            await this.plugin.backup(file, text, "image");
            await this.plugin.app.vault.process(file, (current) => {
              if (current !== text) throw new Error("\u7B14\u8BB0\u5DF2\u53D8\u5316\uFF0C\u5DF2\u53D6\u6D88\u5199\u56DE\uFF1B\u8BF7\u91CD\u65B0\u70B9\u51FB\u56FE\u7247");
              return sameDocumentPatch(current, token, replacement);
            });
          }
        }
        new Notice2(`\u56FE\u7247\u5C3A\u5BF8\u5DF2\u4FDD\u5B58\uFF1A${Math.round(width)}${height === null ? " px\uFF08\u4FDD\u6301\u6BD4\u4F8B\uFF09" : " \xD7 " + Math.round(height) + " px"}`);
      }
      close() {
        const s = this.session;
        this.session = null;
        if (s) {
          s.cleanup?.();
          s.box.remove();
        }
      }
      destroy() {
        this.resolveId++;
        this.close();
        for (const cleanup of this.bindings.values()) cleanup();
        this.bindings.clear();
      }
    };
    module2.exports = { ImageResizeManager: ImageResizeManager2, imageElement, cleanTarget: cleanTarget2 };
  }
});

// src/main.js
var { Plugin, PluginSettingTab, Setting, Modal, Notice, MarkdownView, normalizePath } = require("obsidian");
var { formatNote, scanImages, isImageTarget, isExcalidraw } = require_markdown();
var { captureSelection, commitStyle, HEX } = require_text_style();
var { layoutExtension, applyLayout, decorateTabKnowledge, refreshTabKnowledge } = require_layout();
var { ImageResizeManager, cleanTarget } = require_image_resize();
var DEFAULTS = {
  layoutVersion: 2,
  layoutEnabled: true,
  lineHeight: 1.62,
  blockPadding: 0.28,
  headingH1: 0.95,
  headingH2: 0.82,
  headingH3: 0.7,
  headingH4: 0.58,
  listIndent: 1.8,
  imagePadding: 0.28,
  tablePadding: 0.28,
  splitProseLines: true,
  looseLists: true,
  splitIndentedListParagraphs: true,
  paragraphEnter: true,
  tabKnowledgeLines: true,
  backupEnabled: true,
  imageResize: true,
  readingResize: true,
  freeResize: false,
  maxImageWidth: 4096,
  colors: [
    { name: "\u98CE\u9669\u7EA2", text: "#d64545", background: "#ffd9dc" },
    { name: "\u91CD\u70B9\u6A59", text: "#cb6c13", background: "#ffe1bd" },
    { name: "\u6982\u5FF5\u84DD", text: "#367bd6", background: "#d8eaff" },
    { name: "\u786E\u8BA4\u7EFF", text: "#278653", background: "#d7f3df" },
    { name: "\u63D0\u793A\u7D2B", text: "#8e5ad7", background: "#ebddff" },
    { name: "\u8865\u5145\u7070", text: "#7a7f87", background: "#e4e6e9" }
  ]
};
function loadValidated(saved) {
  const result = JSON.parse(JSON.stringify(DEFAULTS));
  if (!saved || typeof saved !== "object") return result;
  for (const [key, value] of Object.entries(result)) {
    if (typeof value === "boolean" && typeof saved[key] === "boolean") result[key] = saved[key];
  }
  for (const [key, min, max] of [["lineHeight", 1, 2.4], ["blockPadding", 0, 2], ["headingH1", 0, 3], ["headingH2", 0, 3], ["headingH3", 0, 3], ["headingH4", 0, 3], ["listIndent", 1, 4], ["imagePadding", 0, 3], ["tablePadding", 0, 3], ["maxImageWidth", 100, 8192]]) {
    if (key !== "maxImageWidth" && saved.layoutVersion !== 2) continue;
    if (typeof saved[key] === "number" && Number.isFinite(saved[key])) result[key] = Math.max(min, Math.min(max, saved[key]));
  }
  if (Array.isArray(saved.colors)) {
    const colors = saved.colors.slice(0, 12).filter((c) => c && HEX.test(c.text) && HEX.test(c.background)).map((c, i) => ({ name: String(c.name || `\u989C\u8272 ${i + 1}`).slice(0, 40), text: c.text, background: c.background }));
    if (colors.length) result.colors = colors;
  }
  return result;
}
function notifyError(error) {
  new Notice(error.message || String(error), 7e3);
}
var PaletteModal = class extends Modal {
  constructor(plugin, snapshot, kind) {
    super(plugin.app);
    this.plugin = plugin;
    this.snapshot = snapshot;
    this.kind = kind;
  }
  onOpen() {
    this.contentEl.classList.add("tet-modal");
    this.contentEl.createEl("h2", { text: this.kind === "color" ? "\u9009\u62E9\u6587\u5B57\u989C\u8272" : "\u9009\u62E9\u80CC\u666F\u9AD8\u4EAE" });
    this.contentEl.createEl("p", { text: "\u70B9\u51FB\u989C\u8272\u5E94\u7528\u5230\u6253\u5F00\u9762\u677F\u524D\u9009\u4E2D\u7684\u6587\u5B57\u3002", cls: "tet-muted" });
    const grid = this.contentEl.createDiv({ cls: "tet-palette" });
    for (const color of this.plugin.settings.colors) {
      const value = this.kind === "color" ? color.text : color.background;
      const button = grid.createEl("button", { cls: "tet-swatch" });
      const dot = button.createSpan({ cls: "tet-dot" });
      dot.style.backgroundColor = value;
      button.createSpan({ text: color.name });
      button.title = value;
      button.addEventListener("click", () => {
        try {
          commitStyle(this.snapshot, this.kind, value);
          this.close();
        } catch (e) {
          notifyError(e);
        }
      });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var FormatPreviewModal = class extends Modal {
  constructor(plugin, editor, info) {
    super(plugin.app);
    this.plugin = plugin;
    this.editor = editor;
    this.info = info;
    this.original = editor.getValue();
    this.result = formatNote(this.original, plugin.settings);
  }
  onOpen() {
    const el = this.contentEl;
    el.classList.add("tet-modal");
    el.createEl("h2", { text: "\u683C\u5F0F\u5316\u5F53\u524D\u7B14\u8BB0 \xB7 \u9884\u89C8" });
    el.createEl("p", { text: `\u5C06\u63D2\u5165 ${this.result.inserted} \u4E2A\u7A7A\u884C\uFF1B\u4FDD\u62A4 ${this.result.protectedLines} \u884C\u7279\u6B8A\u7ED3\u6784\u3002\u4E0D\u4F1A\u4FEE\u6539\u6587\u5B57\u3001\u56FE\u7247\u94FE\u63A5\u6216\u5C3A\u5BF8\u3002` });
    el.createEl("p", { text: this.plugin.settings.splitProseLines ? "\u5F53\u524D\u6A21\u5F0F\uFF1A\u628A\u8FDE\u7EED\u666E\u901A\u6B63\u6587\u7684\u7269\u7406\u6362\u884C\u5206\u6210\u72EC\u7ACB\u6BB5\u843D\u3002\u82E5\u539F\u7B14\u8BB0\u7528\u6362\u884C\u624B\u5DE5\u6298\u884C\uFF0C\u8BF7\u5173\u95ED\u8BBE\u7F6E\u4E2D\u7684\u201C\u9010\u884C\u5206\u6BB5\u201D\u540E\u518D\u8FD0\u884C\u3002" : "\u5F53\u524D\u6A21\u5F0F\uFF1A\u4FDD\u7559\u6B63\u6587\u624B\u5DE5\u6362\u884C\uFF0C\u53EA\u5206\u9694\u6807\u9898\u3001\u56FE\u7247\u3001\u5217\u8868\u548C\u8868\u683C\u3002", cls: "tet-muted" });
    const columns = el.createDiv({ cls: "tet-format-preview" });
    for (const [label, value] of [["\u539F\u6587", this.original], ["\u683C\u5F0F\u5316\u540E", this.result.text]]) {
      const col = columns.createDiv();
      col.createEl("h3", { text: label });
      const area = col.createEl("textarea");
      area.value = value;
      area.readOnly = true;
      area.setAttribute("aria-label", label);
    }
    new Setting(el).setName("\u786E\u8BA4\u6267\u884C").setDesc(this.plugin.settings.backupEnabled ? "\u9ED8\u8BA4\u5148\u4FDD\u5B58\u539F\u6587\u5907\u4EFD\uFF0C\u518D\u4EE5\u4E00\u6B21\u7F16\u8F91\u66FF\u6362\u5168\u6587\uFF1B\u53EF Ctrl+Z \u64A4\u9500\u3002" : "\u539F\u6587\u5907\u4EFD\u5DF2\u5173\u95ED\uFF1B\u53EF Ctrl+Z \u64A4\u9500\u3002").addButton((button) => button.setButtonText("\u53D6\u6D88").onClick(() => this.close())).addButton((button) => button.setButtonText("\u5E94\u7528\u683C\u5F0F\u5316").setCta().setDisabled(this.result.inserted === 0).onClick(async () => {
      button.setDisabled(true);
      try {
        if (this.editor.getValue() !== this.original || this.info.file?.path !== this.filePath) throw new Error("\u9884\u89C8\u671F\u95F4\u7B14\u8BB0\u5DF2\u53D8\u5316\uFF0C\u8BF7\u91CD\u65B0\u8FD0\u884C\u683C\u5F0F\u5316");
        await this.plugin.backup(this.info.file, this.original, "format");
        if (this.editor.getValue() !== this.original || this.info.file?.path !== this.filePath) throw new Error("\u7B14\u8BB0\u5DF2\u53D8\u5316\uFF0C\u672A\u6267\u884C\u683C\u5F0F\u5316");
        const last = this.editor.lastLine();
        this.editor.transaction({ changes: [{ from: { line: 0, ch: 0 }, to: { line: last, ch: this.editor.getLine(last).length }, text: this.result.text }] });
        this.close();
        new Notice(`\u5DF2\u63D2\u5165 ${this.result.inserted} \u4E2A\u7A7A\u884C\uFF0C\u53EF Ctrl+Z \u64A4\u9500`);
      } catch (e) {
        notifyError(e);
        button.setDisabled(false);
      }
    }));
    this.filePath = this.info.file?.path;
  }
  onClose() {
    this.contentEl.empty();
  }
};
var SizeModal = class extends Modal {
  constructor(plugin, source) {
    super(plugin.app);
    this.plugin = plugin;
    this.source = source;
  }
  onOpen() {
    const el = this.contentEl;
    el.classList.add("tet-modal");
    el.createEl("h2", { text: "\u8BBE\u7F6E\u56FE\u7247\u5C3A\u5BF8" });
    el.createEl("p", { text: this.source.token.target, cls: "tet-muted" });
    const current = this.source.token.raw.match(/\\?\|(\d+)(?:x(\d+))?(?=\\?\||\]\])/);
    let width = current?.[1] || "320", height = current?.[2] || "";
    new Setting(el).setName("\u5BBD\u5EA6\uFF08px\uFF09").addText((t) => t.setValue(width).onChange((v) => width = v));
    new Setting(el).setName("\u9AD8\u5EA6\uFF08px\uFF09").setDesc("\u7559\u7A7A\u5219\u4FDD\u6301\u539F\u6BD4\u4F8B\uFF1B\u8F93\u5165\u9AD8\u5EA6\u5219\u4FDD\u5B58\u5BBD\xD7\u9AD8\u3002").addText((t) => t.setValue(height).onChange((v) => height = v));
    new Setting(el).addButton((b) => b.setButtonText("\u4FDD\u5B58\u5230\u7B14\u8BB0").setCta().onClick(async () => {
      try {
        await this.plugin.images.commit(this.source, Number(width), height.trim() ? Number(height) : null);
        this.close();
      } catch (e) {
        notifyError(e);
      }
    }));
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TraderSettings = class extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const p = this.plugin, s = p.settings, el = this.containerEl;
    el.empty();
    el.createEl("h2", { text: "\u4EA4\u6613\u5458\u7F16\u8F91\u589E\u5F3A / Trader Editor Tools" });
    el.createEl("p", { text: "\u683C\u5F0F\u5316\u53EA\u5728\u4E3B\u52A8\u8FD0\u884C\u547D\u4EE4\u5E76\u786E\u8BA4\u9884\u89C8\u540E\u4FEE\u6539\u7B14\u8BB0\u3002\u56FE\u7247\u5C3A\u5BF8\u53EA\u5728\u5B8C\u6210\u62D6\u52A8\u6216\u70B9\u51FB\u4FDD\u5B58\u540E\u5199\u56DE\u3002", cls: "tet-muted" });
    const toggle = (name, description, key) => new Setting(el).setName(name).setDesc(description).addToggle((t) => t.setValue(s[key]).onChange(async (value) => {
      s[key] = value;
      await p.saveSettings();
    }));
    const number = (name, key, min, max, step = 1) => new Setting(el).setName(name).addSlider((t) => t.setLimits(min, max, step).setValue(s[key]).setDynamicTooltip().onChange(async (value) => {
      s[key] = value;
      await p.saveSettings();
    }));
    el.createEl("h3", { text: "\u6BB5\u843D\u4E0E\u6392\u7248" });
    toggle("\u542F\u7528\u7EDF\u4E00\u6392\u7248", "\u5F71\u54CD Live Preview\u3001\u9605\u8BFB\u6A21\u5F0F\u548C PDF\uFF1B\u4E0D\u6539\u5199\u7B14\u8BB0\u6E90\u7801\u3002", "layoutEnabled");
    number("\u6B63\u6587\u5185\u90E8\u884C\u8DDD\uFF08\u500D\uFF09", "lineHeight", 1, 2.4, 0.01);
    number("\u6B63\u6587 / \u9876\u5C42\u5217\u8868\u6BCF\u4FA7\u7559\u767D\uFF08em\uFF09", "blockPadding", 0, 2, 0.01);
    number("H1 \u4E0A\u4E0B\u6BCF\u4FA7\u7559\u767D\uFF08em\uFF09", "headingH1", 0, 3, 0.01);
    number("H2 \u4E0A\u4E0B\u6BCF\u4FA7\u7559\u767D\uFF08em\uFF09", "headingH2", 0, 3, 0.01);
    number("H3 \u4E0A\u4E0B\u6BCF\u4FA7\u7559\u767D\uFF08em\uFF09", "headingH3", 0, 3, 0.01);
    number("H4\u2013H6 \u4E0A\u4E0B\u6BCF\u4FA7\u7559\u767D\uFF08em\uFF09", "headingH4", 0, 3, 0.01);
    number("\u5217\u8868\u7F29\u8FDB\uFF08em\uFF09", "listIndent", 1, 4, 0.1);
    number("\u56FE\u7247\u4E0A\u4E0B\u6BCF\u4FA7\u7559\u767D\uFF08em\uFF09", "imagePadding", 0, 3, 0.01);
    number("\u8868\u683C\u4E0A\u4E0B\u6BCF\u4FA7\u7559\u767D\uFF08em\uFF09", "tablePadding", 0, 3, 0.01);
    new Setting(el).setName("\u6062\u590D\u5DF2\u9A8C\u8BC1 WoLai \u57FA\u51C6").setDesc("\u6B63\u6587\u884C\u8DDD 1.62\uFF1B\u6B63\u6587\u548C\u9876\u5C42\u5217\u8868\u6BCF\u4FA7 0.28em\uFF1B\u6807\u9898\u4E0A\u4E0B\u5BF9\u79F0\u3002\u4E0D\u4F1A\u4FEE\u6539\u7B14\u8BB0\u3002").addButton((b) => b.setButtonText("\u6062\u590D\u57FA\u51C6").onClick(async () => {
      for (const key of ["layoutVersion", "lineHeight", "blockPadding", "headingH1", "headingH2", "headingH3", "headingH4", "listIndent", "imagePadding", "tablePadding"]) s[key] = DEFAULTS[key];
      await p.saveSettings();
      this.display();
    }));
    toggle("\u683C\u5F0F\u5316\uFF1A\u9010\u884C\u5206\u6BB5", "\u666E\u901A\u6B63\u6587\u6BCF\u4E2A\u7269\u7406\u6362\u884C\u72EC\u7ACB\u6210\u6BB5\uFF1B\u9876\u5C42\u5217\u8868\u540E\u672A\u7F29\u8FDB\u6B63\u6587\u4E5F\u72EC\u7ACB\u6210\u6BB5\u3002\u539F\u7B14\u8BB0\u7528\u8F6F\u6362\u884C\u5EF6\u7EED\u5217\u8868\u6216\u624B\u5DE5\u6298\u884C\u65F6\u8BF7\u5173\u95ED\u3002\u81EA\u52A8\u6298\u884C\u3001\u786C\u6362\u884C\u548C\u5D4C\u5957\u5217\u8868\u4FDD\u7559\u3002", "splitProseLines");
    toggle("\u683C\u5F0F\u5316\uFF1A\u5206\u9694\u9876\u5C42\u5217\u8868\u9879", "\u4E3A\u9876\u5C42\u5144\u5F1F\u5217\u8868\u9879\u589E\u52A0\u7A7A\u884C\uFF1B\u5D4C\u5957\u5217\u8868\u5185\u5BB9\u4FDD\u6301\u539F\u6837\u3002", "looseLists");
    toggle("\u683C\u5F0F\u5316\uFF1A\u5206\u9694\u5217\u8868\u5185\u7F29\u8FDB\u6B63\u6587", "\u4E3A\u5217\u8868\u9879\u540E\u7684\u666E\u901A\u7F29\u8FDB\u6B63\u6587\u8865\u7A7A\u884C\uFF0C\u4FDD\u7559\u539F\u7F29\u8FDB\u548C\u5D4C\u5957\u5C42\u7EA7\u3002\u4EE3\u7801\u3001\u5F15\u7528\u3001\u591A\u884C HTML / \u5F3A\u8C03\u4E0E\u786C\u6362\u884C\u4E0D\u62C6\u3002\u5148\u68C0\u67E5\u9884\u89C8\u3002", "splitIndentedListParagraphs");
    toggle("\u666E\u901A\u6B63\u6587 Enter \u81EA\u52A8\u5206\u6BB5", "\u7F16\u8F91\u6A21\u5F0F\u5728\u666E\u901A\u6B63\u6587\u672B\u5C3E\u6309\u4E00\u6B21 Enter \u63D2\u5165\u6BB5\u843D\u7A7A\u884C\uFF1B\u53EF\u5173\u95ED\u3002\u5217\u8868\u3001\u5F15\u7528\u3001\u4EE3\u7801\u548C\u6E90\u7801\u6A21\u5F0F\u7EE7\u7EED\u4F7F\u7528 Obsidian \u539F\u884C\u4E3A\u3002\u65E7\u7B14\u8BB0\u4E0D\u4F1A\u81EA\u52A8\u6539\u5199\u3002", "paragraphEnter");
    toggle("Tab \u7F29\u8FDB\u6309\u77E5\u8BC6\u884C\u663E\u793A", "\u72EC\u7ACB Tab \u7F29\u8FDB\u5757\u4E2D\uFF0C\u6BCF\u4E2A\u7269\u7406\u884C\u90FD\u4F7F\u7528\u4E0E\u5217\u8868\u9879\u76F8\u540C\u7684\u5757\u95F4\u8DDD\uFF1B\u81EA\u52A8\u6298\u884C\u4ECD\u7D27\u51D1\u3002\u9605\u8BFB/PDF \u540C\u6B65\u663E\u793A\u3002\u4EE3\u7801\u56F4\u680F\u548C\u7A7A\u683C\u7F29\u8FDB\u4EE3\u7801\u4E0D\u53D7\u5F71\u54CD\uFF1B\u82E5 Tab \u672C\u6765\u8868\u793A\u7A0B\u5E8F\u4EE3\u7801\uFF0C\u8BF7\u5173\u95ED\u3002\u53EA\u6539\u53D8\u663E\u793A\uFF0C\u4E0D\u5199\u6B63\u6587\u3002", "tabKnowledgeLines");
    toggle("\u4FDD\u5B58\u539F\u6587\u5907\u4EFD", "\u683C\u5F0F\u5316\u3001\u9605\u8BFB\u6A21\u5F0F\u56FE\u7247\u5199\u56DE\u524D\uFF0C\u5728\u672C\u63D2\u4EF6 backups \u76EE\u5F55\u4FDD\u5B58\u539F\u6587\u3002\u5907\u4EFD\u4E0D\u4F1A\u81EA\u52A8\u5220\u9664\u3002", "backupEnabled");
    new Setting(el).setName("\u5907\u4EFD\u4F4D\u7F6E").setDesc(`${p.app.vault.configDir}/plugins/${p.manifest.id}/backups/`);
    el.createEl("h3", { text: "\u56FE\u7247\u62D6\u62FD\u7F29\u653E" });
    toggle("\u542F\u7528\u56FE\u7247\u62D6\u62FD", "\u70B9\u51FB\u56FE\u7247\u51FA\u73B0\u56DB\u89D2\u63A7\u5236\u70B9\uFF1B\u62D6\u52A8\u9ED8\u8BA4\u4FDD\u6301\u6BD4\u4F8B\uFF0CAlt \u81EA\u7531\u8C03\u6574\uFF0CEsc \u53D6\u6D88\u3002", "imageResize");
    toggle("\u5141\u8BB8\u9605\u8BFB\u6A21\u5F0F\u8C03\u6574", "\u9605\u8BFB\u6A21\u5F0F\u8C03\u6574\u4E5F\u4F1A\u5199\u56DE Markdown\uFF1B\u6CA1\u6709\u7F16\u8F91\u7A97\u683C\u65F6\u5148\u4FDD\u5B58\u539F\u6587\u5907\u4EFD\u3002", "readingResize");
    toggle("\u9ED8\u8BA4\u81EA\u7531\u5BBD\u9AD8", "\u5F00\u542F\u540E\u76F4\u63A5\u62D6\u52A8\u4FDD\u5B58\u5BBD\xD7\u9AD8\uFF1B\u5173\u95ED\u65F6\u6309 Alt \u4E34\u65F6\u81EA\u7531\u8C03\u6574\u3002", "freeResize");
    number("\u62D6\u62FD\u6700\u5927\u5BBD\u5EA6\uFF08px\uFF09", "maxImageWidth", 100, 8192, 10);
    new Setting(el).setName("Excalidraw \u68C0\u6D4B").setDesc(p.excalidrawAvailable() ? "\u5DF2\u68C0\u6D4B\u5230\u542F\u7528\u7684 Excalidraw\uFF1B\u4F7F\u7528\u539F\u751F\u5D4C\u5165\u5C3A\u5BF8\u8BED\u6CD5\u3002" : "\u672A\u68C0\u6D4B\u5230\u542F\u7528\u7684 Excalidraw\u3002\u666E\u901A\u56FE\u7247\u548C\u5176\u4ED6\u529F\u80FD\u7167\u5E38\u53EF\u7528\uFF1B\u7ED8\u56FE\u9700\u542F\u7528 Excalidraw \u540E\u6D4B\u8BD5\u3002");
    el.createEl("h3", { text: "\u5E38\u7528\u989C\u8272" });
    el.createEl("p", { text: "\u6BCF\u884C\u4F9D\u6B21\u4E3A\u540D\u79F0\u3001\u6587\u5B57\u8272\u3001\u80CC\u666F\u8272\u3002\u524D 9 \u884C\u5BF9\u5E94\u56FA\u5B9A\u5FEB\u6377\u952E\u69FD\u4F4D\uFF1B\u6D45\u8272\u9AD8\u4EAE\u9ED8\u8BA4\u6DF1\u8272\u524D\u666F\uFF0C\u5DF2\u8BBE\u7F6E\u7684\u6587\u5B57\u8272\u4F1A\u4FDD\u7559\u3002", cls: "tet-muted" });
    s.colors.forEach((color, index) => {
      new Setting(el).setName(`\u69FD\u4F4D ${index + 1}`).addText((t) => t.setValue(color.name).onChange(async (v) => {
        color.name = v.trim().slice(0, 40) || `\u989C\u8272 ${index + 1}`;
        await p.saveSettings();
      })).addColorPicker((t) => {
        t.inputEl.setAttribute("aria-label", "\u6587\u5B57\u989C\u8272");
        t.inputEl.title = "\u6587\u5B57\u989C\u8272";
        t.setValue(color.text).onChange(async (v) => {
          color.text = v;
          await p.saveSettings();
        });
      }).addColorPicker((t) => {
        t.inputEl.setAttribute("aria-label", "\u80CC\u666F\u8272");
        t.inputEl.title = "\u80CC\u666F\u8272";
        t.setValue(color.background).onChange(async (v) => {
          color.background = v;
          await p.saveSettings();
        });
      }).addExtraButton((b) => b.setIcon("trash-2").setTooltip("\u5220\u9664\u989C\u8272\uFF1B\u540E\u7EED\u69FD\u4F4D\u524D\u79FB").onClick(async () => {
        if (s.colors.length === 1) return new Notice("\u8BF7\u81F3\u5C11\u4FDD\u7559\u4E00\u4E2A\u989C\u8272");
        s.colors.splice(index, 1);
        await p.saveSettings();
        this.display();
      }));
    });
    new Setting(el).setName("\u6DFB\u52A0\u989C\u8272").addButton((b) => b.setButtonText("\u6DFB\u52A0").setDisabled(s.colors.length >= 12).onClick(async () => {
      s.colors.push({ name: `\u989C\u8272 ${s.colors.length + 1}`, text: "#367bd6", background: "#d8eaff" });
      await p.saveSettings();
      this.display();
    }));
    new Setting(el).setName("\u6062\u590D\u9ED8\u8BA4\u914D\u8272").addButton((b) => b.setButtonText("\u6062\u590D").onClick(async () => {
      s.colors = JSON.parse(JSON.stringify(DEFAULTS.colors));
      await p.saveSettings();
      this.display();
    }));
  }
};
module.exports = class TraderEditorTools extends Plugin {
  async onload() {
    this.settings = loadValidated(await this.loadData());
    this.cmViews = /* @__PURE__ */ new Set();
    this.documents = /* @__PURE__ */ new Set();
    this.images = new ImageResizeManager(this);
    this.bindDocument(this.app.workspace.containerEl.ownerDocument);
    this.app.workspace.iterateAllLeaves((leaf) => this.bindDocument(leaf.view.containerEl.ownerDocument));
    this.registerEvent(this.app.workspace.on("window-open", (_, window) => this.bindDocument(window.document)));
    this.registerEvent(this.app.workspace.on("window-close", (_, window) => this.documents.delete(window.document)));
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => this.images.close()));
    this.registerEvent(this.app.workspace.on("file-open", () => {
      this.images.resolveId++;
      this.images.close();
    }));
    this.registerEditorExtension(layoutExtension(this));
    this.registerMarkdownPostProcessor((el, ctx) => this.images.annotate(el, ctx));
    this.registerMarkdownPostProcessor((el, ctx) => decorateTabKnowledge(el, ctx, this.settings));
    this.addSettingTab(new TraderSettings(this.app, this));
    this.addCommand({ id: "format-note", name: "\u683C\u5F0F\u5316\u5F53\u524D\u7B14\u8BB0\uFF08\u9884\u89C8 / \u5907\u4EFD\uFF09", editorCallback: (editor, info) => {
      if (!info.file) return new Notice("\u8BF7\u5148\u4FDD\u5B58\u7B14\u8BB0");
      if (/\.excalidraw(?:\.md)?$/i.test(info.file.path) || /^excalidraw-plugin:/m.test(editor.getValue().slice(0, 1e3))) return new Notice("\u4E0D\u683C\u5F0F\u5316 Excalidraw \u7ED8\u56FE\u6587\u4EF6\uFF0C\u8BF7\u5728\u666E\u901A Markdown \u7B14\u8BB0\u4E2D\u4F7F\u7528");
      new FormatPreviewModal(this, editor, info).open();
    } });
    this.addCommand({ id: "set-image-size", name: "\u8BBE\u7F6E\u5149\u6807\u5904\u56FE\u7247\u5C3A\u5BF8", editorCallback: (editor, info) => {
      try {
        const text = editor.getValue(), pos = editor.posToOffset(editor.getCursor());
        const tokens = this.imageTokens(text, info.file?.path || "").filter((t) => pos >= t.start && pos <= t.end);
        if (tokens.length !== 1) throw new Error("\u8BF7\u628A\u5149\u6807\u653E\u5230\u56FE\u7247\u7684 Markdown \u8BED\u6CD5\u5185\u90E8\uFF08\u53EF\u5207\u6362\u6E90\u7801\u6A21\u5F0F\u5B9A\u4F4D\uFF09");
        const token = tokens[0], resolved = this.app.metadataCache.getFirstLinkpathDest(cleanTarget(token.target), info.file.path);
        new SizeModal(this, { file: info.file, editor, info, text, token, resolvedPath: resolved?.path, notePath: info.file.path }).open();
      } catch (e) {
        notifyError(e);
      }
    } });
    const style = (kind, editor, info, value) => {
      try {
        const snapshot = captureSelection(editor, info.file);
        snapshot.info = info;
        if (kind === "color" || kind === "highlight") {
          if (value) commitStyle(snapshot, kind, value);
          else new PaletteModal(this, snapshot, kind).open();
        } else commitStyle(snapshot, kind);
      } catch (e) {
        notifyError(e);
      }
    };
    for (const [kind, name] of [["color", "\u8BBE\u7F6E\u6587\u5B57\u989C\u8272\u2026"], ["highlight", "\u8BBE\u7F6E\u80CC\u666F\u9AD8\u4EAE\u2026"], ["underline", "\u5207\u6362\u4E0B\u5212\u7EBF"], ["clear", "\u6E05\u9664\u9009\u4E2D\u6587\u5B57\u6837\u5F0F"]]) {
      this.addCommand({ id: "style-" + kind, name, editorCallback: (editor, info) => style(kind, editor, info) });
    }
    for (let i = 0; i < 9; i++) for (const [kind, label] of [["color", "\u6587\u5B57\u989C\u8272"], ["highlight", "\u80CC\u666F\u9AD8\u4EAE"]]) {
      this.addCommand({ id: `${kind}-slot-${i + 1}`, name: `${label}\uFF1A\u69FD\u4F4D ${i + 1}`, editorCallback: (editor, info) => {
        const color = this.settings.colors[i];
        if (!color) return new Notice("\u6B64\u989C\u8272\u69FD\u4F4D\u5C1A\u672A\u8BBE\u7F6E");
        style(kind, editor, info, kind === "color" ? color.text : color.background);
      } });
    }
    this.registerEvent(this.app.workspace.on("editor-menu", (menu, editor, info) => {
      if (!editor.getSelection()) return;
      let snapshot;
      try {
        snapshot = captureSelection(editor, info.file);
        snapshot.info = info;
      } catch (_) {
        return;
      }
      menu.addSeparator();
      for (const [kind, label, icon] of [["color", "\u4EA4\u6613\u5458\u5DE5\u5177\uFF1A\u6587\u5B57\u989C\u8272\u2026", "palette"], ["highlight", "\u4EA4\u6613\u5458\u5DE5\u5177\uFF1A\u80CC\u666F\u9AD8\u4EAE\u2026", "highlighter"], ["underline", "\u4EA4\u6613\u5458\u5DE5\u5177\uFF1A\u5207\u6362\u4E0B\u5212\u7EBF", "underline"], ["clear", "\u4EA4\u6613\u5458\u5DE5\u5177\uFF1A\u6E05\u9664\u6587\u5B57\u6837\u5F0F", "eraser"]]) {
        menu.addItem((item) => item.setTitle(label).setIcon(icon).onClick(() => {
          try {
            if (kind === "color" || kind === "highlight") new PaletteModal(this, snapshot, kind).open();
            else commitStyle(snapshot, kind);
          } catch (e) {
            notifyError(e);
          }
        }));
      }
    }));
  }
  bindDocument(doc) {
    this.documents.add(doc);
    applyLayout(doc, this.settings);
    this.images.bind(doc);
  }
  async saveSettings() {
    await this.saveData(this.settings);
    for (const doc of this.documents) {
      applyLayout(doc, this.settings);
      refreshTabKnowledge(doc, this.settings);
    }
    for (const view of this.cmViews) view.dispatch({});
  }
  excalidrawAvailable() {
    try {
      return !!this.app.plugins?.getPlugin?.("obsidian-excalidraw-plugin");
    } catch (_) {
      return false;
    }
  }
  imageTokens(text, notePath) {
    return scanImages(text).map((token) => {
      const file = this.app.metadataCache.getFirstLinkpathDest(cleanTarget(token.target), notePath);
      const fm = file ? this.app.metadataCache.getFileCache(file)?.frontmatter : null;
      if (fm && Object.prototype.hasOwnProperty.call(fm, "excalidraw-plugin")) token.isDrawing = true;
      return token;
    }).filter((token) => isImageTarget(token.target) || isExcalidraw(token));
  }
  async backup(file, text, reason) {
    if (!this.settings.backupEnabled || !file) return;
    const folder = normalizePath(`${this.app.vault.configDir}/plugins/${this.manifest.id}/backups`);
    const adapter = this.app.vault.adapter;
    if (!await adapter.exists(folder)) {
      try {
        await adapter.mkdir(folder);
      } catch (e) {
        if (!await adapter.exists(folder)) throw e;
      }
    }
    const stamp = (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-");
    const base = file.basename.replace(/[\\/:*?"<>|]/g, "_");
    const path = normalizePath(`${folder}/${base}-${stamp}-${reason}-${Math.random().toString(36).slice(2, 7)}.md`);
    await adapter.write(path, text);
  }
  onunload() {
    this.images?.destroy();
    for (const doc of this.documents || []) {
      refreshTabKnowledge(doc, null);
      doc.body.classList.remove("tet-enabled");
      doc.getElementById("tet-layout-vars")?.remove();
    }
    this.cmViews?.clear();
  }
};
