const { build } = require('esbuild');
const path = require('node:path');
const fs = require('node:fs');
const root = path.resolve(__dirname, '..');
const manifest = require('../manifest.json');
// Include bundled-parser licenses even when main.js is downloaded on its own.
const thirdPartyNotice = fs.readFileSync(path.join(root, 'THIRD-PARTY-NOTICES.md'), 'utf8').replace(/\r\n/g, '\n').trim();
build({
  entryPoints: [path.join(root, 'src/main.js')],
  outfile: path.join(root, 'main.js'),
  bundle: true,
  platform: 'browser',
  format: 'cjs',
  target: 'es2020',
  external: ['obsidian', '@codemirror/view', '@codemirror/state'],
  banner: { js: `/* ${manifest.name} v${manifest.version} | MIT | Generated by scripts/build.cjs\n\n${thirdPartyNotice}\n*/` },
  logLevel: 'info',
}).catch(() => process.exit(1));
