const { build } = require('esbuild');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const manifest = require('../manifest.json');
build({
  entryPoints: [path.join(root, 'src/main.js')],
  outfile: path.join(root, 'main.js'),
  bundle: true,
  platform: 'browser',
  format: 'cjs',
  target: 'es2020',
  external: ['obsidian', '@codemirror/view', '@codemirror/state'],
  banner: { js: `/* Trader Editor Tools v${manifest.version} | MIT | Generated by scripts/build.cjs */` },
  logLevel: 'info',
}).catch(() => process.exit(1));
